export { IconTelegram } from './icon-telegram'
export { IconNotion } from './icon-notion'
export { IconFigma } from './icon-figma'
export { IconTrello } from './icon-trello'
export { IconSlack } from './icon-slack'
export { IconZoom } from './icon-zoom'
export { IconStripe } from './icon-stripe'
export { IconGmail } from './icon-gmail'
export { IconMedium } from './icon-medium'
export { IconSkype } from './icon-skype'
export { IconDocker } from './icon-docker'
export { IconGithub } from './icon-github'
export { IconGitlab } from './icon-gitlab'
export { IconDiscord } from './icon-discord'
export { IconWhatsapp } from './icon-whatsapp'
export { IconFacebook } from './icon-facebook'

